<?xml version="1.0" encoding="utf-8"?><Database Name="QLHS" Class="QLHSDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-2UMFTUC;Initial Catalog=QLHS;Persist Security Info=True;User ID=sa" SettingsObjectName="StudentManagement.Properties.Settings" SettingsPropertyName="QLHSConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.LopHoc" Member="LopHocs">
    <Type Name="LopHoc">
      <Column Name="LopHocID" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLopHoc" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="LopHoc_HocSinh" Member="HocSinhs" ThisKey="LopHocID" OtherKey="LopHocID" Type="HocSinh" />
    </Type>
  </Table>
  <Table Name="dbo.HocSinh" Member="HocSinhs">
    <Type Name="HocSinh">
      <Column Name="HocSinhID" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenHocSinh" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NamSinh" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DiemTrungBinh" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="QueQuan" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LopHocID" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Association Name="LopHoc_HocSinh" Member="LopHoc" ThisKey="LopHocID" OtherKey="LopHocID" Type="LopHoc" IsForeignKey="true" />
    </Type>
  </Table>
</Database>